# Generated by Django 3.2.7 on 2021-10-07 20:34

from django.db import migrations, models
import django_cryptography.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjunctFacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_f_eaf_c_crs_list', django_cryptography.fields.encrypt(models.CharField(choices=[('A', 'A'), ('CRS', 'CRS'), ('F', 'F'), ('C', 'C'), ('EAF', 'EAF')], max_length=3))),
                ('semester', django_cryptography.fields.encrypt(models.CharField(default='--', max_length=4))),
                ('first_name', django_cryptography.fields.encrypt(models.CharField(max_length=30))),
                ('last_name', django_cryptography.fields.encrypt(models.CharField(max_length=30))),
                ('date_of_birth', django_cryptography.fields.encrypt(models.DateField())),
                ('employeeID', django_cryptography.fields.encrypt(models.IntegerField(unique=True))),
                ('step_rate_dept', django_cryptography.fields.encrypt(models.CharField(max_length=10))),
                ('I9_completed', django_cryptography.fields.encrypt(models.DateField(default='NA'))),
                ('I9_greater_than_3_years', django_cryptography.fields.encrypt(models.IntegerField(default='NA'))),
                ('background_passed', django_cryptography.fields.encrypt(models.CharField(choices=[('NA', 'NA'), (' ', ' '), ('--', '--'), ('P', 'pass')], default='NA', max_length=2))),
                ('cv_resume', django_cryptography.fields.encrypt(models.CharField(default='NA', max_length=4))),
                ('masters', django_cryptography.fields.encrypt(models.CharField(default='NA', max_length=30))),
                ('CTL_notified', django_cryptography.fields.encrypt(models.DateField(default='NA'))),
                ('classes', django_cryptography.fields.encrypt(models.TextField())),
                ('address', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('city', django_cryptography.fields.encrypt(models.CharField(max_length=20))),
                ('state', django_cryptography.fields.encrypt(models.CharField(max_length=2))),
                ('zip', django_cryptography.fields.encrypt(models.IntegerField())),
                ('primary_email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('secondary_email', django_cryptography.fields.encrypt(models.EmailField(default='johnDoe@gmail.com', max_length=254))),
                ('primary_phone', django_cryptography.fields.encrypt(phone_field.models.PhoneField(help_text='Primary phone number', max_length=31))),
                ('secondary_phone', django_cryptography.fields.encrypt(phone_field.models.PhoneField(blank=True, default='000-000-0000', help_text='Secondary phone number', max_length=31))),
                ('special_conditions_and_comments', django_cryptography.fields.encrypt(models.TextField())),
                ('semesters_taught', django_cryptography.fields.encrypt(models.TextField())),
                ('archive', django_cryptography.fields.encrypt(models.BooleanField())),
            ],
        ),
    ]
