# Generated by Django 3.2.7 on 2021-09-28 20:00

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjunctFacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_f_eaf_c_crs_list', models.CharField(max_length=3)),
                ('semester', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('employeeID', models.IntegerField()),
                ('I9_completed', models.DateField()),
                ('I9_greater_than_3_years', models.IntegerField()),
                ('background_passed', models.CharField(default='NA', max_length=2)),
                ('cv_resume', models.CharField(default='NA', max_length=4)),
                ('masters', models.CharField(max_length=30)),
                ('CTL_notified', models.DateField()),
                ('classes', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('primary_phone', phone_field.models.PhoneField(blank=True, help_text='Primary phone number', max_length=31)),
                ('secondary_phone', phone_field.models.PhoneField(blank=True, help_text='Secondary phone number', max_length=31)),
                ('special_conditions_and_comments', models.TextField()),
                ('semesters_taught', models.TextField()),
            ],
        ),
    ]
