# Generated by Django 3.2.7 on 2021-10-07 20:34

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('CRS', 'CRS'), ('EAF', 'EAF'), ('A', 'A'), ('C', 'C'), ('F', 'F')], max_length=3)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('P', 'pass'), ('NA', 'NA'), ('--', '--'), (' ', ' ')], default='NA', max_length=2)),
        ),
    ]
