# Generated by Django 3.2.7 on 2021-10-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
