# Generated by Django 3.2.7 on 2021-10-18 01:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_adjunctfacultymember_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='semesters_taught',
        ),
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('F', 'faculty'), ('3', 'step 3'), ('2', 'step 2'), ('1', 'step 1')], default='step 1', max_length=10),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('A', 'A'), ('F', 'F'), ('EAF', 'EAF'), ('C', 'C'), ('CRS', 'CRS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='archived',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('P', 'pass'), ('F', 'fail'), ('NA', 'NA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='cv_resume',
            field=models.IntegerField(help_text='please enter a year'),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='employeeID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='primary_phone',
            field=phone_field.models.PhoneField(help_text='Primary phone number', max_length=31),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_class', models.CharField(max_length=10)),
                ('adjunct_faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.adjunctfacultymember')),
            ],
        ),
    ]
