# Generated by Django 3.2.7 on 2021-11-14 22:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_adjunctfacultymember_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='semesters_taught',
        ),
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('3', 'step 3'), ('2', 'step 2'), ('F', 'faculty'), ('1', 'step 1')], default='step 1', max_length=10),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='CTL_notified',
            field=models.DateField(help_text='Please enter a date.'),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='I9_completed',
            field=models.DateField(help_text='Please enter a date.'),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='I9_greater_than_3_years',
            field=models.IntegerField(help_text='Please enter a number of years.'),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('A', 'A'), ('CRS', 'CRS'), ('C', 'C'), ('F', 'F'), ('EAF', 'EAF')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='archived',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('NA', 'NA'), ('P', 'pass'), ('F', 'fail')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='cv_resume',
            field=models.IntegerField(help_text='please enter a year'),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='employeeID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='primary_phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 1112223333', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='secondary_phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 1112223333', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='semester',
            field=models.CharField(help_text='Please enter in format: semester year (ex: FA19)', max_length=4),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='special_conditions_and_comments',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_class', models.CharField(max_length=10)),
                ('adjunct_faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.adjunctfacultymember')),
            ],
        ),
    ]
