# Generated by Django 3.2.7 on 2021-10-10 01:48

from django.db import migrations, models
import django_cryptography.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_adjunctfacultymember_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='archived',
        ),
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='archive',
            field=django_cryptography.fields.encrypt(models.BooleanField(default=False)),
        ),
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='step_rate_dept',
            field=django_cryptography.fields.encrypt(models.CharField(default='NA', max_length=10)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='CTL_notified',
            field=django_cryptography.fields.encrypt(models.DateField(default='NA')),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='I9_completed',
            field=django_cryptography.fields.encrypt(models.DateField(default='NA')),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='I9_greater_than_3_years',
            field=django_cryptography.fields.encrypt(models.IntegerField(default='NA')),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('F', 'F'), ('CRS', 'CRS'), ('C', 'C'), ('A', 'A'), ('EAF', 'EAF')], max_length=3)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('P', 'pass'), ('--', '--'), (' ', ' '), ('NA', 'NA')], default='NA', max_length=2)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='classes',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='cv_resume',
            field=django_cryptography.fields.encrypt(models.CharField(default='NA', max_length=4)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='employeeID',
            field=django_cryptography.fields.encrypt(models.IntegerField(unique=True)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=django_cryptography.fields.encrypt(models.CharField(default='NA', max_length=30)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='primary_email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='primary_phone',
            field=django_cryptography.fields.encrypt(phone_field.models.PhoneField(help_text='Primary phone number', max_length=31)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='secondary_email',
            field=django_cryptography.fields.encrypt(models.EmailField(default='johnDoe@gmail.com', max_length=254)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='secondary_phone',
            field=django_cryptography.fields.encrypt(phone_field.models.PhoneField(blank=True, default='000-000-0000', help_text='Secondary phone number', max_length=31)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='semester',
            field=django_cryptography.fields.encrypt(models.CharField(default='--', max_length=4)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='semesters_taught',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='special_conditions_and_comments',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='state',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=2)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='zip',
            field=django_cryptography.fields.encrypt(models.IntegerField()),
        ),
    ]
