# Generated by Django 3.2.7 on 2021-11-12 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_adjunctfacultymember_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='adjunctfacultymember',
            name='semesters_taught',
        ),
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('3', 'step 3'), ('F', 'faculty'), ('1', 'step 1'), ('2', 'step 2')], default='step 1', max_length=10),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='I9_greater_than_3_years',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('F', 'F'), ('EAF', 'EAF'), ('C', 'C'), ('CRS', 'CRS'), ('A', 'A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='archived',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('NA', 'NA'), ('P', 'pass'), ('F', 'fail')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='cv_resume',
            field=models.IntegerField(help_text='please enter a 4 digit year'),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='employeeID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='primary_phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='secondary_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='semester',
            field=models.CharField(help_text='please enter SP, FA, or SU followed by a 2 digit year. (ex. SP21)', max_length=4),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='special_conditions_and_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='zip',
            field=models.IntegerField(help_text='please enter a 5 digit zipcode'),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_class', models.CharField(max_length=10)),
                ('adjunct_faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.adjunctfacultymember')),
            ],
        ),
    ]
