# Generated by Django 3.2.7 on 2021-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20211112_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('A', 'A'), ('EAF', 'EAF'), ('CRS', 'CRS'), ('C', 'C'), ('F', 'F')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('NA', 'NA'), ('F', 'fail'), ('P', 'pass')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('1', 'step 1'), ('3', 'step 3'), ('2', 'step 2'), ('F', 'faculty')], default='step 1', max_length=10),
        ),
    ]
