# Generated by Django 3.2.7 on 2021-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20211115_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('A', 'A'), ('CRS', 'CRS'), ('F', 'F'), ('C', 'C'), ('EAF', 'EAF')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('F', 'fail'), ('NA', 'NA'), ('P', 'pass')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('F', 'faculty'), ('3', 'step 3'), ('2', 'step 2'), ('1', 'step 1')], default='step 1', max_length=10),
        ),
    ]
