# Generated by Django 3.2.7 on 2021-10-10 23:19

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20211010_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjunctfacultymember',
            old_name='archive',
            new_name='archived',
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('EAF', 'EAF'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('CRS', 'CRS')], max_length=3)),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('NA', 'NA'), (' ', ' '), ('--', '--'), ('P', 'pass')], default='NA', max_length=2)),
        ),
    ]
