# Generated by Django 3.2.7 on 2021-10-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_auto_20211031_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('EAF', 'EAF'), ('A', 'A'), ('CRS', 'CRS'), ('F', 'F'), ('C', 'C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('P', 'pass'), ('F', 'fail'), ('NA', 'NA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('1', 'step 1'), ('F', 'faculty'), ('2', 'step 2'), ('3', 'step 3')], default='step 1', max_length=10),
        ),
    ]
