# Generated by Django 3.2.7 on 2021-11-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_auto_20211115_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('C', 'C'), ('CRS', 'CRS'), ('EAF', 'EAF'), ('A', 'A'), ('F', 'F')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('P', 'pass'), ('NA', 'NA'), ('F', 'fail')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('F', 'faculty'), ('3', 'step 3'), ('1', 'step 1'), ('2', 'step 2')], default='step 1', max_length=10),
        ),
    ]
