# Generated by Django 3.2.7 on 2021-11-14 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_auto_20211114_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('CRS', 'CRS'), ('F', 'F'), ('EAF', 'EAF'), ('A', 'A'), ('C', 'C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('F', 'fail'), ('P', 'pass'), ('NA', 'NA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='primary_phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 1112223333', regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='secondary_phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 1112223333', regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('F', 'faculty'), ('1', 'step 1'), ('3', 'step 3'), ('2', 'step 2')], default='step 1', max_length=10),
        ),
    ]
