# Generated by Django 3.2.7 on 2021-11-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_auto_20211115_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='I9_greater_than_3_years',
            field=models.DateField(blank=True, help_text='Please enter a date.', null=True),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('CRS', 'CRS'), ('A', 'A'), ('F', 'F'), ('C', 'C'), ('EAF', 'EAF')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('1', 'step 1'), ('F', 'faculty'), ('2', 'step 2'), ('3', 'step 3')], default='step 1', max_length=10),
        ),
    ]
