# Generated by Django 3.2.7 on 2021-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0009_auto_20211031_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('A', 'A'), ('EAF', 'EAF'), ('F', 'F'), ('C', 'C'), ('CRS', 'CRS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('F', 'fail'), ('NA', 'NA'), ('P', 'pass')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('3', 'step 3'), ('F', 'faculty'), ('2', 'step 2'), ('1', 'step 1')], default='step 1', max_length=10),
        ),
    ]
