# Generated by Django 3.2.7 on 2021-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0010_auto_20211031_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('A', 'A'), ('F', 'F'), ('C', 'C'), ('CRS', 'CRS'), ('EAF', 'EAF')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('2', 'step 2'), ('3', 'step 3'), ('1', 'step 1'), ('F', 'faculty')], default='step 1', max_length=10),
        ),
    ]
