# Generated by Django 3.2.7 on 2021-10-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0011_auto_20211031_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('C', 'C'), ('EAF', 'EAF'), ('A', 'A'), ('F', 'F'), ('CRS', 'CRS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('F', 'faculty'), ('3', 'step 3'), ('2', 'step 2'), ('1', 'step 1')], default='step 1', max_length=10),
        ),
    ]
