# Generated by Django 3.2.7 on 2021-10-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0012_auto_20211031_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('C', 'C'), ('EAF', 'EAF'), ('F', 'F'), ('A', 'A'), ('CRS', 'CRS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('F', 'fail'), ('P', 'pass'), ('NA', 'NA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('3', 'step 3'), ('1', 'step 1'), ('2', 'step 2'), ('F', 'faculty')], default='step 1', max_length=10),
        ),
    ]
