# Generated by Django 3.2.7 on 2021-10-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0014_auto_20211031_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('CRS', 'CRS'), ('A', 'A'), ('F', 'F'), ('C', 'C'), ('EAF', 'EAF')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('NA', 'NA'), ('P', 'pass'), ('F', 'fail')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='masters',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('1', 'step 1'), ('2', 'step 2'), ('3', 'step 3'), ('F', 'faculty')], default='step 1', max_length=10),
        ),
    ]
