# Generated by Django 3.2.7 on 2021-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0015_auto_20211031_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='a_f_eaf_c_crs_list',
            field=models.CharField(choices=[('CRS', 'CRS'), ('F', 'F'), ('A', 'A'), ('EAF', 'EAF'), ('C', 'C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='background_passed',
            field=models.CharField(choices=[('P', 'pass'), ('NA', 'NA'), ('F', 'fail')], max_length=2),
        ),
        migrations.AlterField(
            model_name='adjunctfacultymember',
            name='step_rate',
            field=models.CharField(choices=[('F', 'faculty'), ('1', 'step 1'), ('3', 'step 3'), ('2', 'step 2')], default='step 1', max_length=10),
        ),
    ]
