# Generated by Django 3.2.7 on 2021-10-31 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('isRead', models.BooleanField()),
            ],
        ),
    ]
